package pkg

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"github.com/typstify/tpix-cli/bundler"
)

var (
	//go:embed typst.toml
	manifestTemplate []byte
)

const (
	entrypointFile = `// This file is the entrypoint of your package. Generated by tpix-cli.`
)

func createSkeleton(pkgDir string, namespace string, name string, isTemplate bool, author string) (string, error) {
	if name == "" {
		return "", errors.New("invalid package name")
	}

	manifest := bundler.Manifest{
		Package: &bundler.Package{
			Name:        name,
			Version:     "0.1.0",
			Entrypoint:  "lib.typ",
			Authors:     []string{author},
			License:     "",
			Description: "An example package.",
			Homepage:    "",
			Repository:  "",
			Compiler:    detectTypstVersion(),
		},
	}

	if isTemplate {
		manifest.Template = &bundler.Template{
			Path:       "template",
			Entrypoint: "main.typ",
			Thumbnail:  "thumbnail.png", // Make sure user have a thumbnail.
		}
	}

	pkgDir = filepath.Join(pkgDir, name)
	if folderExists(pkgDir) {
		return "", fmt.Errorf("%s already exists", pkgDir)
	}

	err := os.MkdirAll(pkgDir, 0755)
	if err != nil {
		return "", err
	}

	// generate manifest file

	err = generateManifest(manifest, pkgDir)
	if err != nil {
		log.Println("generateManifest error: ", err)
		return "", err
	}

	// create entrypoint file
	err = createTemplateFile(filepath.Join(pkgDir, "lib.typ"), entrypointFile)
	if err != nil {
		return "", err
	}
	err = createTemplateFile(filepath.Join(pkgDir, "LICENSE"), "Put your license text here.")
	if err != nil {
		return "", err
	}

	err = createTemplateFile(filepath.Join(pkgDir, "README.md"), "This is a sample readme file.")
	if err != nil {
		return "", err
	}

	if isTemplate {
		mainBuilder := strings.Builder{}
		mainBuilder.WriteString(entrypointFile)
		mainBuilder.WriteByte('\n')
		mainBuilder.WriteString(fmt.Sprintf("#import \"@%s/%s:0.1.0\"", namespace, name))

		err = createTemplateFile(filepath.Join(pkgDir, "template", "main.typ"), mainBuilder.String())
		if err != nil {
			return "", err
		}
	}

	return pkgDir, nil
}

func createTemplateFile(path string, content string) error {
	if fileExists(path) {
		return nil
	}

	err := os.MkdirAll(filepath.Dir(path), 0755)
	if err != nil {
		return err
	}

	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0755)
	if err != nil {
		return err
	}

	defer file.Close()

	_, err = file.WriteString(content)
	return err
}

func generateManifest(manifest bundler.Manifest, dir string) error {
	dest := filepath.Join(dir, "typst.toml")
	if fileExists(dest) {
		return nil
	}

	file, err := os.OpenFile(dest, os.O_CREATE|os.O_WRONLY, 0755)
	if err != nil {
		return err
	}

	defer file.Close()

	tmpl, err := template.New("typstPkgManifestTmpl").Parse(string(manifestTemplate))
	if err != nil {
		panic("Invalid manifest template")
	}

	return tmpl.Execute(file, manifest)
}

func fileExists(path string) bool {
	return entryExists(path, false)
}

func entryExists(path string, expectDir bool) bool {
	st, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false
		}

		return false
	}

	if expectDir {
		return st.IsDir()
	}

	return !st.IsDir()
}

func folderExists(path string) bool {
	return entryExists(path, true)
}

func detectTypstVersion() string {
	cmd := exec.CommandContext(context.Background(), "typst", "--version")
	out, _ := cmd.Output()

	pat := regexp.MustCompile(`^typst\s+(\S+)`)
	match := pat.FindSubmatch(out)
	if match == nil {
		return strings.TrimSpace(string(out))
	}

	return string(match[1])
}
